#ifndef _WARLOCK_UNICODE_SYMBOLS_H
#define _WARLOCK_UNICODE_SYMBOLS_H

#include <stdint.h>

enum SymbolID
{
    UCS_MIDDLE_DOT,
    UCS_FOUR_DOTS,
    UCS_DIAMOND,
    UCS_FLIPPED_V,
    UCS_ARIES,
    UCS_ESZETT,
    UCS_ANKH,
    UCS_MUSIC_NOTE,
    UCS_CIRCLE,
    UCS_LIGHTNING_BOLT,
    UCS_FILLED_CIRCLE,
    UCS_NEUTER,
    UCS_U_ACUTE,
    UCS_CURRENCY,
    UCS_UP_ARROW,
    UCS_DOWN_ARROW,
    UCS_LEFT_ARROW,
    UCS_RIGHT_ARROW,
    UCS_OMEGA,
    UCS_CIRCLE_BARS,
    UCS_FILLED_CIRCLE_BARS,
    UCS_LEFT_TRIANGLE,
    UCS_UP_TRIANGLE,
    UCS_DOWN_TRIANGLE,
    UCS_THETA,
    UCS_LAMBDA,
    UCS_KOPPA,
    UCS_LOZENGE,
    UCS_CROSS_PRODUCT,
    UCS_SYMBOL_COUNT
};

const uint32_t symbols[UCS_SYMBOL_COUNT] = {
    [UCS_MIDDLE_DOT] = 0x00b7,
    [UCS_FOUR_DOTS] = 0x2237,
    [UCS_DIAMOND] = 0x25c7,
    [UCS_FLIPPED_V] = 0x22CF,
    [UCS_ARIES] = 0x2648,
    [UCS_ESZETT] = 0x00df,
    [UCS_ANKH] = 0x2640,
    [UCS_MUSIC_NOTE] = 0x266A,
    [UCS_CIRCLE] = 0x26AA,
    [UCS_LIGHTNING_BOLT] = 0x03DF,
    [UCS_FILLED_CIRCLE] = 0x25cf,
    [UCS_NEUTER] = 0x26b2,
    [UCS_U_ACUTE] = 0x00da,
    [UCS_CURRENCY] = 0x00A4,
    [UCS_UP_ARROW] = 0x2191,
    [UCS_DOWN_ARROW] = 0x2193,
    [UCS_LEFT_ARROW] = 0x2190,
    [UCS_RIGHT_ARROW] = 0x2192,
    [UCS_OMEGA] = 0x03A9,
    [UCS_CIRCLE_BARS] = 0x29F2,
    [UCS_FILLED_CIRCLE_BARS] = 0x29F3,
    [UCS_LEFT_TRIANGLE] = 0x1F780,
    [UCS_UP_TRIANGLE] = 0x2206,
    [UCS_DOWN_TRIANGLE] = 0x2207,
    [UCS_THETA] = 0x03B8,
    [UCS_LAMBDA] = 0x03BB,
    [UCS_KOPPA] = 0x03DE,
    [UCS_LOZENGE] = 0x29EB,
    [UCS_CROSS_PRODUCT] = 0x2A2F,
};

inline uint32_t getSymbol(SymbolID symbolID)
{
    return symbols[symbolID];
}

#endif // _WARLOCK_UNICODE_SYMBOLS_H